version: "3.3"
services:
  snode:
    image: blocknetdx/servicenode:latest
    restart: unless-stopped
    volumes:
      - /c/Users/LucienPersonal/AppData/Roaming/Blocknet-Docker/data:/opt/blockchain/data
      - /c/Users/LucienPersonal/AppData/Roaming/Blocknet-Docker/config:/opt/blockchain/config
    ports:
      - "41412"
      - "41414"

  xcloud-getpeers:
    image:  xrouterserviceexplorer/xcloud.getpeers.api:latest
    restart: unless-stopped
    ports:
      - "8080:8080"